MODEL:
  WEIGHT: "catalog://ImageNetPretrained/DLA34"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  DETECT_CLASSES: ( "car", 
                    "truck", 
                    "bus", 
                    "trailer", 
                    "construction_vehicle", 
                    "pedestrian",
                    "motorcycle",
                    "bicycle",
                    "traffic_cone",
                    "barrier")
  TRAIN: ("nuScenes_train",)
  TEST: ("nuScenes_train",)
  TRAIN_SPLIT: "train_detect"
  TEST_SPLIT: "val"
  MAX_OBJECTS: 100
SOLVER:
  BASE_LR: 2.5e-4
  STEPS: (5850, 9350)
  MAX_ITERATION: 14500
  IMS_PER_BATCH: 32
